# Generated by Django 2.0.7 on 2018-07-29 00:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='Must be less than 100 characters'), django.core.validators.MinLengthValidator(5, message='Must be at least 5 characters')])),
                ('description', models.CharField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.MinLengthValidator(5, message='Must be at least 5 characters')])),
                ('status', models.CharField(choices=[('NO', 'no'), ('YES', 'yes')], default='NO', max_length=4)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
