# Generated by Django 2.0.6 on 2018-07-06 03:19

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='Must be less than 100 characters'), django.core.validators.MinLengthValidator(5, message='Must be at least 5 characters')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
