# Generated by Django 2.0.6 on 2018-07-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NO', 'no'), ('YES', 'yes')], default='NO', max_length=4),
        ),
    ]
